# Generated by Django 6.0.5 on 2026-05-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefenseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('level', models.CharField(choices=[('D0', 'D0'), ('D1', 'D1'), ('D2', 'D2'), ('D3', 'D3'), ('custom', 'Custom')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('yaml_path', models.CharField(blank=True, max_length=1024)),
                ('parameters_json', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ModelEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('provider', models.CharField(choices=[('lmstudio', 'LM Studio'), ('ollama', 'Ollama'), ('openai_compatible', 'OpenAI Compatible'), ('other', 'Other')], max_length=40)),
                ('model_name', models.CharField(max_length=255)),
                ('base_url', models.URLField(max_length=1024)),
                ('default_temperature', models.FloatField(default=0.2)),
                ('default_max_tokens', models.PositiveIntegerField(default=1024)),
                ('context_window', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_check_at', models.DateTimeField(blank=True, null=True)),
                ('last_check_status', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
