# Generated by Django 6.0.5 on 2026-05-11 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(choices=[('run_config', 'Run config'), ('preflight', 'Preflight'), ('cases', 'Cases'), ('summary', 'Summary'), ('report', 'Report'), ('csv', 'CSV'), ('figure', 'Figure'), ('log', 'Log'), ('other', 'Other')], default='other', max_length=40)),
                ('file_path', models.CharField(max_length=1024)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='experiments.benchmarkrun')),
            ],
            options={
                'ordering': ['run', 'artifact_type', 'id'],
            },
        ),
    ]
