# Generated by Django 6.0.5 on 2026-05-11 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0001_initial'),
        ('configs_app', '0001_initial'),
        ('datasets', '0001_initial'),
        ('experiments', '0002_benchmarkrun_extra_params_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('artifact_type', models.CharField(choices=[('dataset', 'Dataset'), ('config', 'Config'), ('run_artifact', 'Run artifact'), ('report', 'Report'), ('table', 'Table'), ('figure', 'Figure'), ('json', 'JSON'), ('jsonl', 'JSONL'), ('log', 'Log'), ('markdown', 'Markdown'), ('document', 'Document'), ('script', 'Script'), ('other', 'Other')], default='other', max_length=40)),
                ('file_path', models.CharField(max_length=1024, unique=True)),
                ('source_dir', models.CharField(blank=True, max_length=120)),
                ('extension', models.CharField(blank=True, max_length=20)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('line_count', models.PositiveIntegerField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_artifacts', to='datasets.dataset')),
                ('related_defense_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_artifacts', to='configs_app.defenseprofile')),
                ('related_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_artifacts', to='experiments.benchmarkrun')),
            ],
            options={
                'ordering': ['source_dir', 'artifact_type', 'file_path'],
            },
        ),
    ]
